#!/bin/bash
set -u

# 変数設定
readonly HENG_DIR="$HOME/.heng_dir"
readonly HENG_BRANCH="develop"
readonly HENG_GIT="https://scm.osdn.net/gitroot/hengband/hengband.git"

readonly MOD_DIR="$HOME/.heng_dir/mod"
readonly EDIT_DIR="$HOME/.heng_dir/hengband/lib/edit"
readonly SRC_DIR="$HOME/.heng_dir/hengband/src"

# ソースダウンロード
#: <<'__EOT__'
if [ -e $HENG_DIR/hengband ]; then
  rm -rf $HENG_DIR/hengband
fi
cd $HENG_DIR
git clone --depth=1 -b $HENG_BRANCH --single-branch $HENG_GIT
#__EOT__

# 文字コード変換
nkf -e --overwrite $HENG_DIR/hengband/src/*.c

nkf -e --overwrite $HENG_DIR/hengband/src/a*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/b*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/c*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/d*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/e*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/f*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/g*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/i*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/k*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/l*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/m*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/o*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/p*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/r*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/s*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/t*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/u*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/w*/*.c

nkf -e --overwrite $HENG_DIR/hengband/src/a*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/b*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/c*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/d*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/e*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/f*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/g*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/i*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/k*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/l*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/m*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/o*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/p*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/r*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/s*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/t*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/u*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/w*/*.h


# modファイル交換
diff -s $MOD_DIR/d_info_org.txt $EDIT_DIR/d_info.txt >/dev/null 2>&1
if [[ $? == 0 ]]; then
  rm -rf $EDIT_DIR/d_info.txt;
  cp $MOD_DIR/d_info.txt $EDIT_DIR
  else
  echo " Check --- d_info"
fi

diff -s $MOD_DIR/k_info_org.txt $EDIT_DIR/k_info.txt >/dev/null 2>&1
if [ $? -eq 0 ]; then
  rm -rf $EDIT_DIR/k_info.txt
  cp $MOD_DIR/k_info.txt $EDIT_DIR
  else
  echo " Check --- k_info"
fi

diff -s $MOD_DIR/player-status-table_org.c $SRC_DIR/player/player-status-table.c >/dev/null 2>&1
if [ $? -eq 0 ]; then
  rm -rf $EDIT_DIR/player-status-table.c
  cp $MOD_DIR/player-status-table.c $SRC_DIR/player
  else
  echo " Check --- player-status-table.c"
fi

diff -s $MOD_DIR/q_warg_org.txt $EDIT_DIR/q_warg.txt >/dev/null 2>&1
if [ $? -eq 0 ]; then
  rm -rf $EDIT_DIR/q_warg.txt
  cp $MOD_DIR/q_warg.txt $EDIT_DIR
  else
  echo " Check --- q_warg.txt"
fi

diff -s $MOD_DIR/q0dumpwitness_org.txt $EDIT_DIR/q0dumpwitness.txt >/dev/null 2>&1
if [ $? -eq 0 ]; then
  rm -rf $EDIT_DIR/q0dumpwitness.txt
  cp $MOD_DIR/q0dumpwitness.txt $EDIT_DIR
  else
  echo " Check --- q0dumpwitness.txt"
fi

diff -s $MOD_DIR/q0000001_org.txt $EDIT_DIR/q0000001.txt >/dev/null 2>&1
if [ $? -eq 0 ]; then
  rm -rf $EDIT_DIR/q0000001.txt
  cp $MOD_DIR/q0000001.txt $EDIT_DIR
  else
  echo " Check --- q0000001.txt"
fi

diff -s $MOD_DIR/store-owners_org.c $SRC_DIR/store/store-owners.c >/dev/null 2>&1
if [ $? -eq 0 ]; then
  rm -rf $EDIT_DIR/store-owners.c
  cp $MOD_DIR/store-owners.c $SRC_DIR/store
  else
  echo " Check --- store-owners.c"
fi


# コンパイル
cd $HENG_DIR/hengband
./bootstrap &&
./configure --enable-xft >/dev/null 2>&1 &&
make -j4 install >/dev/null 2>&1

# フォルダのリンクとファイル削除
rm -rf $HENG_DIR/hengband/lib/save
ln -sf $HENG_DIR/save $HENG_DIR/hengband/lib

if [ ! -e $HENG_DIR/apex/scores.raw ]; then
  touch $HENG_DIR/apex/scores.raw
fi

rm -rf $HENG_DIR/hengband/lib/apex
ln -sf $HENG_DIR/apex $HENG_DIR/hengband/lib
