#!/bin/bash
set -eu

echo
echo "　インストール開始　"
echo

#変数設定
readonly ANG_DIR="$HOME/.angband/Hengband"
readonly BREW_DIR="/usr/local/opt/heng"
readonly HENG_CONFIG_VERSION=01
readonly HENG_DIR="$HOME/.heng_dir"
readonly HENG_BRANCH="develop"
readonly HENG_GIT="https://scm.osdn.net/gitroot/hengband/hengband.git"

# ディレクトリ設定
mkdir -p $HENG_DIR/apex
mkdir -p $HENG_DIR/save
mkdir -p $ANG_DIR
ln -nsf $ANG_DIR $HENG_DIR/user
if [ ! -e $HENG_DIR/heng.config ]; then
  cp $BREW_DIR/heng.config $HENG_DIR/heng.config
fi
cp $BREW_DIR/heng.config $HENG_DIR/${HENG_CONFIG_VERSION}_heng.config

# ソースダウンロード
if [ -e $HENG_DIR/hengband ]; then
  rm -rf $HENG_DIR/hengband
fi
cd $HENG_DIR
git clone --depth=1 -b $HENG_BRANCH --single-branch $HENG_GIT
sleep 5

# 文字コード変換
nkf -e --overwrite $HENG_DIR/hengband/src/*.c

nkf -e --overwrite $HENG_DIR/hengband/src/a*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/b*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/c*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/d*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/e*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/f*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/g*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/i*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/k*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/l*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/m*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/o*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/p*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/r*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/s*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/t*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/u*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/w*/*.c

nkf -e --overwrite $HENG_DIR/hengband/src/a*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/b*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/c*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/d*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/e*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/f*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/g*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/i*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/k*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/l*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/m*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/o*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/p*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/r*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/s*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/t*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/u*/*.h
nkf -e --overwrite $HENG_DIR/hengband/src/w*/*.h

# コンパイル
cd $HENG_DIR/hengband
./bootstrap &&
./configure --enable-xft &&
echo
echo "　コンパイル開始　しばらくお待ち下さい　"
echo
sleep 3 &&
make -j4 install 2>/dev/null

# フォルダのリンクとファイル削除
rm -rf $HENG_DIR/hengband/lib/save
ln -sf $HENG_DIR/save $HENG_DIR/hengband/lib

if [ ! -e $HENG_DIR/apex/scores.raw ]; then
  touch $HENG_DIR/apex/scores.raw
fi

rm -rf $HENG_DIR/hengband/lib/apex
ln -sf $HENG_DIR/apex $HENG_DIR/hengband/lib
echo
echo "　インストール完了　"
echo
