#!/bin/bash
set -eu

#変数設定

readonly ANG_DIR="$HOME/.angband/Hengband"
readonly BREW_DIR="/usr/local/opt/heng"
readonly HENG_CONFIG_VERSION=01
readonly HENG_DIR="$HOME/.heng_dir"
readonly HENG_BRANCH="release/3.0.0Alpha"
readonly HENG_GIT="https://scm.osdn.net/gitroot/hengband/hengband.git"

# ディレクトリ設定

mkdir -p $HENG_DIR/apex
mkdir -p $HENG_DIR/save
mkdir -p $ANG_DIR
ln -nsf $ANG_DIR $HENG_DIR/user
cp $BREW_DIR/heng.config $HENG_DIR/${HENG_CONFIG_VERSION}_heng.config

# ソースダウンロード

printf 'Start: Download \n'

if [ -e $HENG_DIR/hengband ]; then
  rm -rf $HENG_DIR/hengband
fi
  
cd $HENG_DIR

git clone --depth=1 -b $HENG_BRANCH --single-branch $HENG_GIT
sleep 5
printf 'Finished: Download \n'

# 文字コード変換

nkf -e --overwrite $HENG_DIR/hengband/src/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/*/*.c
nkf -e --overwrite $HENG_DIR/hengband/src/*/*.h

# コンパイル

printf 'Start: Compile \n'

cd $HENG_DIR/hengband

./bootstrap && ./configure --enable-xft && make -j4 install

printf 'Finished: Compile \n'

# フォルダのリンクとファイル削除

rm -rf $HENG_DIR/hengband/lib/save
ln -sf $HENG_DIR/save $HENG_DIR/hengband/lib

if [ ! -e $HENG_DIR/apex/scores.raw ]; then
  touch $HENG_DIR/apex/scores.raw
fi
rm -rf $HENG_DIR/hengband/lib/apex
ln -sf $HENG_DIR/apex $HENG_DIR/hengband/lib

printf 'Finished: install \n'