#!/bin/bash

brew update && brew reinstall heng ||  printf 'Error: update \n' ; exit 0

printf 'heng-command update complete.\n'

cd $HOME/hengdir/hengband

git fetch && git merge ||  printf 'Error: update \n' ; exit 0

printf 'hengband update complete.\n'
